#!/bin/bash

echo "🚀 Deploying Building API to Server"
echo "====================================="

# Server configuration
SERVER_HOST="172.22.0.19"
SERVER_USER="root"
DEPLOY_DIR="/var/www/building-api"

echo "📁 Deploy directory: $DEPLOY_DIR"
echo "🖥️  Server: $SERVER_USER@$SERVER_HOST"

echo ""
echo "📋 Manual deployment steps:"
echo "=========================="
echo ""
echo "1. SSH to server:"
echo "   ssh $SERVER_USER@$SERVER_HOST"
echo ""
echo "2. Go to project directory:"
echo "   cd $DEPLOY_DIR"
echo ""
echo "3. Pull latest code:"
echo "   git pull origin main"
echo ""
echo "4. Stop existing containers:"
echo "   docker-compose -f docker-compose.prod.yml down"
echo ""
echo "5. Remove old volumes (if needed):"
echo "   docker-compose -f docker-compose.prod.yml down -v"
echo ""
echo "6. Build and start containers:"
echo "   docker-compose -f docker-compose.prod.yml up -d --build"
echo ""
echo "7. Wait for services to start:"
echo "   sleep 30"
echo ""
echo "8. Run database migrations:"
echo "   docker-compose -f docker-compose.prod.yml exec web python manage.py migrate"
echo ""
echo "9. Create superuser (if needed):"
echo "   docker-compose -f docker-compose.prod.yml exec web python manage.py shell -c \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin', 'admin@uzswlu.uz', 'admin123') if not User.objects.filter(username='admin').exists() else print('Superuser already exists')\""
echo ""
echo "10. Collect static files:"
echo "    docker-compose -f docker-compose.prod.yml exec web python manage.py collectstatic --noinput"
echo ""
echo "11. Test API:"
echo "    curl http://localhost:5001/api/health/"
echo ""
echo "12. Check container status:"
echo "    docker-compose -f docker-compose.prod.yml ps"
echo ""
echo "✅ After deployment, test these URLs:"
echo "   - API: https://building.api.uzswlu.uz/"
echo "   - Health: https://building.api.uzswlu.uz/api/health/"
echo "   - Admin: https://building.api.uzswlu.uz/admin/"
echo ""
echo "👤 Default Admin Credentials:"
echo "   Username: admin"
echo "   Password: admin123"
