# Generated by Django 5.2.7 on 2025-10-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rttm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='building',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='device',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='device',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='devicelocation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='devicelocation',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='devicetype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='devicetype',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='repairrequest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='repairrequest',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='responsibleperson',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='responsibleperson',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='room',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='room',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='servicelog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='servicelog',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='building',
            name='created_by_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yaratdi (ID)'),
        ),
        migrations.AddField(
            model_name='building',
            name='created_by_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yaratdi'),
        ),
        migrations.AddField(
            model_name='building',
            name='updated_by_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yangiladi (ID)'),
        ),
        migrations.AddField(
            model_name='building',
            name='updated_by_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yangiladi'),
        ),
        migrations.AddField(
            model_name='category',
            name='created_by_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yaratdi (ID)'),
        ),
        migrations.AddField(
            model_name='category',
            name='created_by_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yaratdi'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_by_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yangiladi (ID)'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_by_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yangiladi'),
        ),
        migrations.AddField(
            model_name='device',
            name='created_by_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yaratdi (ID)'),
        ),
        migrations.AddField(
            model_name='device',
            name='created_by_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yaratdi'),
        ),
        migrations.AddField(
            model_name='device',
            name='updated_by_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yangiladi (ID)'),
        ),
        migrations.AddField(
            model_name='device',
            name='updated_by_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yangiladi'),
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='created_by_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yaratdi (ID)'),
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='created_by_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yaratdi'),
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='updated_by_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yangiladi (ID)'),
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='updated_by_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yangiladi'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='created_by_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yaratdi (ID)'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='created_by_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yaratdi'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='updated_by_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yangiladi (ID)'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='updated_by_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yangiladi'),
        ),
        migrations.AddField(
            model_name='repairrequest',
            name='created_by_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yaratdi (ID)'),
        ),
        migrations.AddField(
            model_name='repairrequest',
            name='created_by_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yaratdi'),
        ),
        migrations.AddField(
            model_name='repairrequest',
            name='updated_by_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yangiladi (ID)'),
        ),
        migrations.AddField(
            model_name='repairrequest',
            name='updated_by_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yangiladi'),
        ),
        migrations.AddField(
            model_name='responsibleperson',
            name='created_by_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yaratdi (ID)'),
        ),
        migrations.AddField(
            model_name='responsibleperson',
            name='created_by_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yaratdi'),
        ),
        migrations.AddField(
            model_name='responsibleperson',
            name='updated_by_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yangiladi (ID)'),
        ),
        migrations.AddField(
            model_name='responsibleperson',
            name='updated_by_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yangiladi'),
        ),
        migrations.AddField(
            model_name='room',
            name='created_by_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yaratdi (ID)'),
        ),
        migrations.AddField(
            model_name='room',
            name='created_by_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yaratdi'),
        ),
        migrations.AddField(
            model_name='room',
            name='updated_by_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yangiladi (ID)'),
        ),
        migrations.AddField(
            model_name='room',
            name='updated_by_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yangiladi'),
        ),
        migrations.AddField(
            model_name='servicelog',
            name='created_by_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yaratdi (ID)'),
        ),
        migrations.AddField(
            model_name='servicelog',
            name='created_by_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yaratdi'),
        ),
        migrations.AddField(
            model_name='servicelog',
            name='updated_by_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yangiladi (ID)'),
        ),
        migrations.AddField(
            model_name='servicelog',
            name='updated_by_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Kim yangiladi'),
        ),
    ]
