name: Clean Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          echo "📦 Installing Python dependencies..."
          pip install -r requirements.txt

      - name: Run Django checks
        run: |
          echo "🧪 Running Django checks..."
          python manage.py check
          python manage.py check --deploy

      - name: Build success
        run: |
          echo ""
          echo "✅ =============================================="
          echo "✅ BUILDING API BUILD COMPLETED!"
          echo "✅ =============================================="
          echo ""
          echo "🔗 Ready for manual deployment"
          echo "📋 Next steps:"
          echo "1. Deploy to production server"
          echo "2. Configure domain: https://building.api.uzswlu.uz/"
          echo ""
          echo "👤 Default Admin Credentials:"
          echo "   Username: admin"
          echo "   Password: admin123"
